const { sanitize, beautify } = require("./utils/sanitize");
const fs = require("fs-extra");
const path = require("path");
const { createCanvas, loadImage } = require("canvas");
const traitRules = require("./traitRules");

const width = 1280;
const height = 1280;
const editionSize = 50;

const canvas = createCanvas(width, height);
const ctx = canvas.getContext("2d");

const layersDir = path.join(__dirname, "layers");
const outputDir = path.join(__dirname, "output");

const randomChoice = (arr) => arr[Math.floor(Math.random() * arr.length)];

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

async function loadValidTraits(trait, gender) {
  const folder = path.join(layersDir, trait);
  const allFiles = (await fs.readdir(folder)).filter((f) => f.endsWith(".png"));

  const forbiddenCharPattern = /[’‘“”]/;
  for (const f of allFiles) {
    if (forbiddenCharPattern.test(f)) {
      throw new Error(`🚫 Forbidden character found in file name: "${f}"`);
    }
  }

  const rules = traitRules[trait] || {};
  const maleOnly = rules.male_only || [];
  const femaleOnly = rules.female_only || [];

  return allFiles
    .filter((file) => {
      const name = path.parse(file).name;
      if (maleOnly.includes(name)) return gender === "male";
      if (femaleOnly.includes(name)) return gender === "female";
      return true; // default: neutral
    })
    .map((file) => ({
      filename: file,
      value: path.parse(file).name,
      path: path.join(folder, file),
    }));
}

async function generateImage(edition) {
  ctx.clearRect(0, 0, width, height);
  const gender = Math.random() < 0.5 ? "male" : "female";
  const attributes = [];

  // === Background
  const bgFolder = path.join(layersDir, "background");
  const bgFiles = (await fs.readdir(bgFolder)).filter((f) =>
    f.endsWith(".png")
  );
  const bgFile = randomChoice(bgFiles);
  const bgImg = await loadImage(path.join(bgFolder, bgFile));
  ctx.drawImage(bgImg, 0, 0, width, height);
  attributes.push({
    trait_type: "Background",
    value: capitalize(path.parse(bgFile).name),
  });

  // === Type (Alien, etc)
  const typeFolder = path.join(layersDir, "type", gender);
  const typeFiles = (await fs.readdir(typeFolder)).filter((f) =>
    f.endsWith(".png")
  );
  const typeFile = randomChoice(typeFiles);
  const typeImg = await loadImage(path.join(typeFolder, typeFile));
  ctx.drawImage(typeImg, 0, 0, width, height);
  attributes.push({
    trait_type: "Type",
    value: capitalize(path.parse(typeFile).name),
  });

  // === Body, Head, Face
  for (const trait of ["body", "head", "face"]) {
    const files = await loadValidTraits(trait, gender);
    const selected = randomChoice(files);
    const img = await loadImage(selected.path);
    ctx.drawImage(img, 0, 0, width, height);

    attributes.push({
      trait_type: capitalize(trait),
      value: beautify(selected.value),
    });
  }

  // === Save image
  const filename = `${edition.toString().padStart(4, "0")}.png`;
  await fs.ensureDir(path.join(outputDir, "images"));
  await fs.writeFile(
    path.join(outputDir, "images", filename),
    canvas.toBuffer("image/png")
  );

  // === Save metadata
  const metadata = {
    name: `Parodee #${edition}`,
    description: "Generated by Parodee NFT Generator",
    image: `ipfs://CID/${filename}`,
    edition,
    attributes,
  };
  await fs.ensureDir(path.join(outputDir, "metadata"));
  await fs.writeJson(
    path.join(outputDir, "metadata", `${edition}.json`),
    metadata,
    { spaces: 2 }
  );

  console.log(`✅ Parodee #${edition} (${gender}) generated`);
}

async function main() {
  await fs.emptyDir(path.join(outputDir, "images"));
  await fs.emptyDir(path.join(outputDir, "metadata"));

  for (let i = 1; i <= editionSize; i++) {
    await generateImage(i);
  }
}

main();
